#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: py-automata-cli-runner help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help py-automata-cli-runner
fi

lasher _help py-automata-cli-runner "$command"
