#!/usr/bin/env bash
#
# Summary: Sync Python Dependencies
#
# Usage: py-automata-cli-runner-_sync-python-deps
#

set -e
#set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
BASE_LIB_FOLDER=${bin_path}/../lib

# Load Python version helper
source ${BASE_LIB_FOLDER}/python_helpers.bash

isPythonDepsOnSync

if [ "$PYTHON_DEPS_ON_SYNC" = "false" ]; then
    echo "Python Deps out of sync, syncing ..."
    installPythonDeps
    commitOnSync
    echo "Changes Committed"
fi